os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="SDL2/2.0.4"
    - CONAN_USERNAME="lasote"
    - CONAN_CHANNEL="testing"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1
    - CONAN_STABLE_BRANCH_PATTERN="release/*"

  matrix:
    # Update the recipe only
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
